# Generated by Django 3.2.25 on 2024-06-05 13:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('judge', '0145_site_data_batch_prerequisites'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polygon_id', models.IntegerField(unique=True)),
                (
                    'problem_code',
                    models.CharField(
                        max_length=20,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator('^[a-z0-9]+$', 'Problem code must be ^[a-z0-9]+$'),
                        ],
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'author',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='problem_sources', to='judge.profile',
                    ),
                ),
                (
                    'main_submission',
                    models.ForeignKey(
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='polygon_imports',
                        to='judge.submission',
                    ),
                ),
                (
                    'problem',
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='polygon_source',
                        to='judge.problem',
                    ),
                ),
            ],
            options={
                'permissions': (('import_problems', 'Import problems from Polygon'),),
            },
        ),
        migrations.CreateModel(
            name='ProblemSourceImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'status',
                    models.CharField(
                        choices=[('P', 'Processing'), ('C', 'Completed'), ('F', 'Failed')], default='P', max_length=2,
                    ),
                ),
                ('log', models.TextField(null=True)),
                ('error', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'author',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='problem_imports', to='judge.profile',
                    ),
                ),
                (
                    'problem_source',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='imports', to='polygon.problemsource',
                    ),
                ),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
