# Generated by Django 3.2.25 on 2024-07-09 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0146_comment_revision_count_v2'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='freeze_time',
            field=models.DurationField(blank=True, null=True, verbose_name='freeze time'),
        ),
    ]
