name: makemessages
on:
  push:
    branches:
      - master
jobs:
  makemessages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Checkout submodules
      run: |
        git submodule init
        git submodule update
    - name: Install requirements
      run: |
         wget https://github.com/jgm/pandoc/releases/download/3.1.8/pandoc-3.1.8-1-amd64.deb
         sudo dpkg -i pandoc-3.1.8-1-amd64.deb
         sudo apt-get install gettext
         curl -O https://artifacts.crowdin.com/repo/deb/crowdin3.deb
         sudo dpkg -i crowdin3.deb
         pip install -r requirements.txt
         pip install pymysql
    - name: Collect localizable strings
      run: |
        echo "STATIC_ROOT = '/tmp'" > dmoj/local_settings.py
        python manage.py makemessages -l en -e py,html,txt
        python manage.py makemessages -l en -d djangojs
    - name: Upload strings to Crowdin
      env:
        CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_API_TOKEN }}
      run: crowdin upload sources
